language: swift
branches:
  only:
    - master
    - next
cache:
  directories:
  - build
  - vendor
  - /usr/local/Homebrew
  - $HOME/Library/Caches/Homebrew
env:
  global:
  - LANG=en_US.UTF-8
  - LC_ALL=en_US.UTF-8
skip_cleanup: true
jobs:
  include:
  - stage: carthage
    osx_image: xcode10
    before_install:
    - brew update
    - brew outdated carthage || brew upgrade carthage
    script:
    - carthage build --no-skip-current

  - stage: podspec
    osx_image: xcode10
    script:
    - pod spec lint

  - stage: check Maps example
    osx_image: xcode10
    script:
    - xcodebuild -scheme Maps -sdk iphonesimulator clean build

  - stage: check Stocks example
    osx_image: xcode10
    script:
    - xcodebuild -scheme Stocks -sdk iphonesimulator clean build

  - stage: check Samples example
    osx_image: xcode10
    script:
    - xcodebuild -scheme Samples -sdk iphonesimulator clean build
